### ISSUE TITLE
i supposed that u should write a poc for every subject

### ISSUE THREAD

**Issue by qdwjfufu** [s4n7h0/xvwa#22]
there should be some details

**Comment by s4n7h0** [comment]
@qdwjfufu The exercises are to try out and learn rather than replicating from pre-solved walk-through. The code is already available when you deploy it locally. I suggest you to go through the exercises. Nevertheless the exercises are not very complex, indeed fundamentals.  There should be multiple methods to exploit and post exploit each issues. I would like to see blog posts on that from the users of XVWA. 

// closing this issue as it is not related to the project code itself.
